apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend       # ← captures the frontend pods
  ports:
    - port: 80           # port to access the Service
      targetPort: 80     # container port (nginx listens here)
