apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend      # ← capture pods with this label
  ports:
    - port: 8080         # port to access Service
      targetPort: 8080   # port where container listens (containerPort)
